CREATE TABLE TBL_DFS_NAMESPACE (
	id VARCHAR(20) NOT NULL,
	name VARCHAR(200) NOT NULL,
	url VARCHAR(200) NOT NULL,
	status VARCHAR(10) NOT NULL,
	description VARCHAR(500),
	createTime TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX URL_UNI ON TBL_DFS_NAMESPACE (url);

CREATE UNIQUE INDEX NAME_UNI ON TBL_DFS_NAMESPACE (name);
