/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.agile.upload.entity {

    [Bindable]
    [RemoteClass(alias="org.agile.upload.entity.FileItem")]
    public class FileItem extends FileItemBase {
    }
}