/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (NodeItem.as).
 */

package org.agile.dfs.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class NodeItemBase implements IExternalizable {

        private var _ip:String;
        private var _load:int;
        private var _port:int;
        private var _status:String;
        private var _type:String;

        public function set ip(value:String):void {
            _ip = value;
        }
        public function get ip():String {
            return _ip;
        }

        public function set load(value:int):void {
            _load = value;
        }
        public function get load():int {
            return _load;
        }

        public function set port(value:int):void {
            _port = value;
        }
        public function get port():int {
            return _port;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        public function readExternal(input:IDataInput):void {
            _ip = input.readObject() as String;
            _load = input.readObject() as int;
            _port = input.readObject() as int;
            _status = input.readObject() as String;
            _type = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_ip);
            output.writeObject(_load);
            output.writeObject(_port);
            output.writeObject(_status);
            output.writeObject(_type);
        }
    }
}